<template>
    <div class="loadingio-spinner-cube-an02ig4jkq">
        <div class="ldio-fvic3x0ncmc">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'MvSpinner'
}
</script>

<style type="text/css">
@keyframes ldio-fvic3x0ncmc {
    0% {
        transform: scale(1.2400000000000002);
    }
    100% {
        transform: scale(1);
    }
}
.ldio-fvic3x0ncmc div {
    position: absolute;
    width: 75.96px;
    height: 75.96px;
    top: 19.69333333333334px;
    left: 19.69333333333334px;
    background: #4f7abe;
    animation: ldio-fvic3x0ncmc 0.819672131147541s cubic-bezier(0, 0.5, 0.5, 1)
        infinite;
    animation-delay: -0.2459016393442623s;
}
.ldio-fvic3x0ncmc div:nth-child(2) {
    top: 19.69333333333334px;
    left: 115.34666666666666px;
    background: #0a7142;
    animation-delay: -0.1639344262295082s;
}
.ldio-fvic3x0ncmc div:nth-child(3) {
    top: 115.34666666666666px;
    left: 19.69333333333334px;
    background: #4f7abe;
    animation-delay: 0s;
}
.ldio-fvic3x0ncmc div:nth-child(4) {
    top: 115.34666666666666px;
    left: 115.34666666666666px;
    background: #13a365;
    animation-delay: -0.0819672131147541s;
}
.loadingio-spinner-cube-an02ig4jkq {
    width: 211px;
    height: 211px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
}
.ldio-fvic3x0ncmc {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-fvic3x0ncmc div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
